# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-25 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='identifier',
            field=models.CharField(choices=[(b'user_doc', 'User Document'), (b'not_specified', 'Not Specified')], default=b'not_specified', max_length=100, verbose_name='Document Identifier'),
        ),
    ]
