# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-25 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userdocument'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdocument',
            old_name='file',
            new_name='filename',
        ),
    ]
