# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-26 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181126_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocument',
            name='extension',
            field=models.CharField(default='png', help_text='Document extension like png, jpeg etc..', max_length=10, verbose_name='Document Extension'),
            preserve_default=False,
        ),
    ]
