# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-26 11:55
from __future__ import unicode_literals

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userdocument_extension'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usersession',
            managers=[
                ('objects', users.models.UserSessionManager()),
            ],
        ),
    ]
